name: Build Game iOS 🚀

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 6000.3.11f1
          targetPlatform: iOS
          projectPath: .
          # Dòng này để nó tự hiểu là bản Personal
          versioning: Semantic
