name: Get Unity License 🔑

on: workflow_dispatch

jobs:
  get_license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Activation File
        uses: game-ci/unity-request-activation-file@v2.3.0 # Dùng bản cụ thể này
        with:
          unityVersion: 6000.0.31f1 # Thử dùng bản này để máy chủ dễ nhận diện
